# -*- coding: utf-8 -*-
"""크롤링 11주차(정유민).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gw4g-2flU7m0TZHRRwP2MkmQhx3DzEfW
"""

!pip install beautifulsoup4
!pip install requests

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')
# %cd /content/drive/MyDrive/Crawling
!pwd
!ls

from urllib.request import HTTPPasswordMgrWithDefaultRealm
import requests
from bs4 import BeautifulSoup
import csv
import time

url="https://bce.pusan.ac.kr/bce/50178/subview.do"

BEdd=[]#BE전공분야
BEii=[]#BE전공개요
BEss=[]#BE진로

def get_data(url) :
    response=requests.get(url)
    if response.status_code==200 :
      html=response.text
      soup=BeautifulSoup(html, 'html.parser')

      BEmenu=soup.find("div", attrs={'id':'menu50178_obj20'})
      BEstyle=BEmenu.find("ul")
      BEintro=BEstyle.find_all("span")
      for i in BEintro:
         BEii.append(i.get_text().strip())

      BEmenu=soup.find("div", attrs={'id':'menu50178_obj20'})
      BEdom=BEmenu.find("ol")
      BEdd.append(BEdom.get_text().strip())

      BEmenu=soup.find("div", attrs={'id':'menu50178_obj20'})
      BEstyle=BEmenu.find_all("ul")
      for i in BEstyle :
        BEss.append(i.get_text().strip())

    else :
      print('연결되지 않음.')
      print(response.status_code)
  
    return BEdd

k=input('DS 또는 BE를 입력해주세요: ')
url='https://bce.pusan.ac.kr/bce/50178/subview.do'
get_data(url)

if k == 'BE':
  for i in BEii:
    print(f'<전공개요> {i}')
    print(f'<진로 및 취업> {BEss[3]}')
  for i in BEdd : 
    print(f'<전공분야>\n{i}')